# Generated by Django 4.2.4 on 2023-08-29 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QwizModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('internet_store', 'internet_store'), ('landing_page', 'landing_page'), ('corporation_site', 'corporation_site'), ('not_sure', 'not_sure')], default=('not_sure', 'not_sure'), max_length=55)),
                ('style_logo', models.CharField(max_length=15)),
                ('creativity', models.CharField(max_length=55)),
                ('functionality', models.CharField(max_length=55)),
                ('website', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(max_length=55)),
                ('phone', models.CharField(max_length=15)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
