# Generated by Django 4.2.4 on 2023-08-29 06:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('type', models.CharField(choices=[('internet_store', 'internet_store'), ('landing_page', 'landing_page'), ('corporation_site', 'corporation_site')], max_length=125)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='portfolio/')),
                ('yuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('info', models.TextField()),
            ],
        ),
    ]
