# Generated by Django 4.2.4 on 2023-08-29 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliomodel',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
