# Generated by Django 4.2.4 on 2023-08-29 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodel',
            name='comment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
