# Generated by Django 4.1.7 on 2023-09-01 02:56

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField(default=datetime.date.today)),
                ('info', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='articles/')),
                ('yuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('type', models.CharField(choices=[('project', 'project'), ('news', 'news'), ('team', 'team'), ('article', 'article'), ('mass_media', 'mass_media')], max_length=50)),
            ],
        ),
    ]
