# Generated by Django 4.2.4 on 2023-08-29 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlesmodel',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='articles/'),
        ),
    ]
